### ISSUE TITLE
Not clear HOW the board would connect 

### ISSUE THREAD

**Issue by tekntrash** [analogdevicesinc/pyadi-iio#621] opened 2024-12-12 12:13 UTC
We are trying this repo on a AD2S1210 board attached to a SDP board EVAL-SDP-CB1Z

But when we run this:
import adi
sdr = adi.ad2s1210()

we get 

ERROR: Unable to create Avahi DNS-SD browser: Invalid host name
ERROR: Unable to create Avahi DNS-SD browser: Invalid host name
Traceback (most recent call last):
  File "/root/openvla-env/lib/python3.10/site-packages/adi/context_manager.py", line 32, in __init__
    self._ctx = iio.Context(self._uri_auto)
  File "/root/openvla-env/lib/python3.10/site-packages/iio.py", line 1328, in __init__
    self._context = _new_uri(_context.encode("ascii"))
  File "/root/openvla-env/lib/python3.10/site-packages/iio.py", line 56, in _check_null
    raise OSError(err, _strerror(err))
OSError: [Errno 6] No such device or address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/lixo.py", line 4, in <module>
    sdr = adi.ad2s1210()
  File "/root/openvla-env/lib/python3.10/site-packages/adi/ad2s1210.py", line 20, in __init__
    context_manager.__init__(self, uri, self._device_name)
  File "/root/openvla-env/lib/python3.10/site-packages/adi/context_manager.py", line 38, in __init__
    raise Exception("No device found")
Exception: No device found

So, it's not clear if the problem is with the AD2S1210 board or the SDP board EVAL-SDP-CB1Z, as we don't know if this library uses that USB board

**Comment by tfcollins** [comment] 2024-12-17 21:49
Duplicate of https://github.com/analogdevicesinc/pyadi-iio/issues/622

**Closed by tfcollins** 2024-12-17 21:49 UTC
